/* Auto-generated by tools/install_icons.sh. Do not edit manually. */
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#if LVGL_VERSION_MAJOR >= 9
typedef lv_image_dsc_t tabler_icon_dsc_t;
#else
typedef lv_img_dsc_t tabler_icon_dsc_t;
#endif

extern const tabler_icon_dsc_t tabler_icon_api_book_S;
extern const tabler_icon_dsc_t tabler_icon_api_book_P;
extern const tabler_icon_dsc_t tabler_icon_api_book_L;
extern const tabler_icon_dsc_t tabler_icon_anchor_S;
extern const tabler_icon_dsc_t tabler_icon_anchor_P;
extern const tabler_icon_dsc_t tabler_icon_anchor_L;
extern const tabler_icon_dsc_t tabler_icon_sailboat_S;
extern const tabler_icon_dsc_t tabler_icon_sailboat_P;
extern const tabler_icon_dsc_t tabler_icon_sailboat_L;

typedef struct {
    const char *name;
    char variant;
    uint16_t size_px;
    const tabler_icon_dsc_t *icon;
} tabler_icon_registry_entry_t;

extern const tabler_icon_registry_entry_t tabler_icon_registry[];
extern const uint32_t tabler_icon_registry_count;

const tabler_icon_dsc_t *tabler_icon_by_name_variant(const char *name, char variant);
const tabler_icon_dsc_t *tabler_icon_by_name_size(const char *name, uint16_t size_px);

#ifdef __cplusplus
}
#endif
