/* Auto-generated by tools/install_icons.py. Do not edit manually. */
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#if LVGL_VERSION_MAJOR >= 9
typedef lv_image_dsc_t tabler_icon_dsc_t;
#else
typedef lv_img_dsc_t tabler_icon_dsc_t;
#endif

extern const tabler_icon_dsc_t tabler_icon_api_book_S;
extern const tabler_icon_dsc_t tabler_icon_api_book_P;
extern const tabler_icon_dsc_t tabler_icon_api_book_L;
extern const tabler_icon_dsc_t tabler_icon_api_book_N;
extern const tabler_icon_dsc_t tabler_icon_anchor_S;
extern const tabler_icon_dsc_t tabler_icon_anchor_P;
extern const tabler_icon_dsc_t tabler_icon_anchor_L;
extern const tabler_icon_dsc_t tabler_icon_anchor_N;
extern const tabler_icon_dsc_t tabler_icon_sailboat_S;
extern const tabler_icon_dsc_t tabler_icon_sailboat_P;
extern const tabler_icon_dsc_t tabler_icon_sailboat_L;
extern const tabler_icon_dsc_t tabler_icon_sailboat_N;
extern const tabler_icon_dsc_t tabler_icon_loader_2_S;
extern const tabler_icon_dsc_t tabler_icon_loader_2_P;
extern const tabler_icon_dsc_t tabler_icon_loader_2_L;
extern const tabler_icon_dsc_t tabler_icon_loader_2_N;
extern const tabler_icon_dsc_t tabler_icon_alert_square_rounded_S;
extern const tabler_icon_dsc_t tabler_icon_alert_square_rounded_P;
extern const tabler_icon_dsc_t tabler_icon_alert_square_rounded_L;
extern const tabler_icon_dsc_t tabler_icon_alert_square_rounded_N;
extern const tabler_icon_dsc_t tabler_icon_triangle_filled_S;
extern const tabler_icon_dsc_t tabler_icon_triangle_filled_P;
extern const tabler_icon_dsc_t tabler_icon_triangle_filled_L;
extern const tabler_icon_dsc_t tabler_icon_triangle_filled_N;
extern const tabler_icon_dsc_t tabler_icon_settings_S;
extern const tabler_icon_dsc_t tabler_icon_settings_P;
extern const tabler_icon_dsc_t tabler_icon_settings_L;
extern const tabler_icon_dsc_t tabler_icon_settings_N;
extern const tabler_icon_dsc_t tabler_icon_ripple_S;
extern const tabler_icon_dsc_t tabler_icon_ripple_P;
extern const tabler_icon_dsc_t tabler_icon_ripple_L;
extern const tabler_icon_dsc_t tabler_icon_ripple_N;
extern const tabler_icon_dsc_t tabler_icon_assets_compass_north_svgrepo_com_svg_S;
extern const tabler_icon_dsc_t tabler_icon_assets_compass_north_svgrepo_com_svg_P;
extern const tabler_icon_dsc_t tabler_icon_assets_compass_north_svgrepo_com_svg_L;
extern const tabler_icon_dsc_t tabler_icon_assets_compass_north_svgrepo_com_svg_N;

typedef struct {
    const char *name;
    char variant;
    uint16_t size_px;
    const tabler_icon_dsc_t *icon;
} tabler_icon_registry_entry_t;

extern const tabler_icon_registry_entry_t tabler_icon_registry[];
extern const uint32_t tabler_icon_registry_count;

const tabler_icon_dsc_t *tabler_icon_by_name_variant(const char *name, char variant);
const tabler_icon_dsc_t *tabler_icon_by_name_size(const char *name, uint16_t size_px);

#ifdef __cplusplus
}
#endif
